# Generated by Django 5.1.7 on 2025-09-30 17:30

import achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_contactmessage_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL', null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload achievement image or certificate', null=True, upload_to=achievements.models.achievement_image_path),
        ),
    ]
