# Generated by Django 5.1.7 on 2025-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_image_url_alter_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
